modLoader="javafml"
loaderVersion="[41,)"
issueTrackerURL="https://github.com/Mrbysco/RallyHealth/issues"
license="MIT"

[[mods]]
modId="rallyhealth"
version="${file.jarVersion}"
displayName="Rally Health"
displayURL="https://www.curseforge.com/minecraft/mc-mods/rally-health"
authors="Mrbysco"
description='''
Adds the Rally system from Bloodborne to Minecraft.
'''
[[dependencies.rallyhealth]]
modId="minecraft"
mandatory=true
versionRange="[1.19,1.20)"
ordering="NONE"
side="BOTH"
[[dependencies.rallyhealth]]
modId="forge"
mandatory=true
versionRange="[41.1.0,)"
ordering="NONE"
side="BOTH"