modLoader="javafml"
loaderVersion="[45,)"
issueTrackerURL="https://github.com/Mrbysco/RallyHealth/issues"
license="MIT"

[[mods]]
modId="rallyhealth"
version="${file.jarVersion}"
displayName="Rally Health"
displayURL="https://www.curseforge.com/minecraft/mc-mods/rally-health"
authors="Mrbysco"
description='''
Adds the Rally system from Bloodborne to Minecraft.
'''
[[dependencies.rallyhealth]]
modId="minecraft"
mandatory=true
versionRange="[1.19.4,1.20)"
ordering="NONE"
side="BOTH"
