modLoader="javafml"
loaderVersion="[1,)"
issueTrackerURL="https://github.com/Mrbysco/RallyHealth/issues"
license="MIT"

[[mods]]
modId="rallyhealth"
version="${file.jarVersion}"
displayName="Rally Health"
displayURL="https://www.curseforge.com/minecraft/mc-mods/rally-health"
authors="Mrbysco"
description='''
Adds the Rally system from Bloodborne to Minecraft.
'''
[[dependencies.rallyhealth]]
modId="minecraft"
mandatory=true
versionRange="[1.20.2,1.21)"
ordering="NONE"
side="BOTH"
[[dependencies.rallyhealth]]
modId="neoforge"
mandatory=true
versionRange="[20.2.64-beta,)"
ordering="NONE"
side="BOTH"
